Sticky_Notes/urls.py
"""
URL Configuration
https://docs.djangoproject.com/en/2.2/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings, views

urlpatterns = [
    path('notes/', include('notes.urls')),
    path('admin/', admin.site.urls),
    path('', views.index)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

notes/urls.py
from django.urls import path
from . import views

app_name='notes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:note_id>/delete', views.delete, name='delete'),
    path('<int:note_id>/update', views.update, name='update'),
    path('add/', views.add, name='add')
]

notes/models.py
from django.db import models

class Note(models.Model):
    title = models.CharField(max_length=10000)
    created_at = models.DateTimeField('Created', auto_now_add=True)
    update_at = models.DateTimeField('Updated', auto_now=True)
    isCompleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

Sticky_Notes/views.py
from django.shortcuts import redirect

def index(request):
    return redirect('/notes')

notes/views.py
from django.shortcuts import get_object_or_404, redirect #render
from django.views import generic
from .models import Note
#from django.http import HttpResponseRedirect

class IndexView(generic.ListView):
    template_name = 'notes/index.html'
    context_object_name = 'note_list'

    def get_queryset(self):
        """Return all the latest notes."""
        return Note.objects.order_by('-created_at')

def add(request):
    title = request.POST['title']
    Note.objects.create(title=title)

    return redirect('notes:index')

def delete(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    note.delete()

    return redirect('notes:index')

def update(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    isCompleted = request.POST.get('isCompleted', False)
    if isCompleted == 'on':
        isCompleted = True
    
    note.isCompleted = isCompleted

    note.save()
    return redirect('notes:index')

notes/templates/notes/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-NhjE/pnk7c+5B5JX3qKjOy/iaCfZJH/7KNzKg+j/On7eORQbmrA/YyV9XrmNl/tot+m72JYhYD7LkjQjwMzJ5g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">    
    <!--- Custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block title %}
  {% endblock %}
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"> 
    </script>
    <script src="https://kit.fontawesome.com/15974f9624.js" crossorigin="anonymous">
    </script>
    {% block content %}
    {% endblock %}  
  </body>
</html>

notes/templates/notes/index.html
{% extends 'notes/base.html' %}
{% block title %}
<title>Sticky Notes</title>
{% endblock %}
{% block content %}
<div class="container">
  <!-- <button id="theme-toggle" class="btn btn-sm btn-outline-dark float-right">
    <i class="fas fa-moon"></i> Dark Mode
  </button> -->
  <!-- title row section -->
  <div class="row">
    <div class="col-lg-9">
      <div class="page-header">
        <h1>
          Sticky Notes
        </h1>
      </div>
    </div>
  </div>
  <!-- add note row section -->
  <div class="row">
    <div class="col-lg-9">
      <form method="post" action="{% url 'notes:add' %}">
        {% csrf_token %}
        <div class="form-row">
          <div class="col-md-6">
            <input type="text" class="form-control" name="title" placeholder="Take a note..." required>
          </div>
          <div class="col-md-6">
            <button type="submit" name="submit" class="btn btn-outline-primary">
              Add Me
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <hr />
  <!-- note list row section-->
  <div class="row">
    <div class="col-lg-6">
      <div class="list-group">
        {% for note in note_list %}
        <div class="list-group-item {% if note.isCompleted %} note-complete {% endif %}">
          <form style="display: inline;" method="post" action="{% url 'notes:update' note.id %}">
            {% csrf_token %}
            <input type="checkbox" name="isCompleted" onchange="this.form.submit()" {% if note.isCompleted %} checked
              {% endif %} class="note-status-checkbox"
              title="{% if not note.isCompleted %} mark as done {% else %} mark undone {% endif %}">
          </form>
          {{ note.title }}
          <a href="{% url 'notes:delete' note.id %}" title="Delete">
            <i class="far fa-trash-alt"></i>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<!-- JavaScript for theme toggle button section -->
<!-- <script>
  function toggleTheme() {
    const body = document.body;
    body.classList.toggle("dark-mode");
    const button = document.getElementById("theme-toggle");
    if (body.classList.contains("dark-mode")) {
      button.innerHTML = '<i class="fas fa-sun"></i> Light Mode';
    } else {
      button.innerHTML = '<i class="fas fa-moon"></i> Dark Mode';
    }
  }
  const themeToggle = document.getElementById("theme-toggle");
  themeToggle.addEventListener("click", toggleTheme);
</script> -->
{% endblock %}

notes/templates/notes/test-index.html
{% extends 'notes/base.html' %}
{% block title %}
<title>Sticky Notes</title>
{% endblock %}
{% block content %}
<div class="container">
  <button id="theme-toggle" class="btn btn-sm btn-outline-dark float-right">
    <i class="fas fa-moon"></i> Dark Mode
  </button>
  <!-- title row section -->
  <div class="row">
    <div class="col-lg-9">
      <div class="page-header">
        <h1>
          Sticky Notes
        </h1>
      </div>
    </div>
  </div>
  <!-- add note row section -->
  <div class="row">
    <div class="col-lg-9">
      <form method="post" action="{% url 'notes:add' %}">
        {% csrf_token %}
        <div class="form-row">
          <div class="col-md-6">
            <input type="text" class="form-control" name="title" placeholder="Take a note..." required>
          </div>
          <div class="col-md-6">
            <button type="submit" name="submit" class="btn btn-outline-primary">
              Add Me
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <hr />
  <!-- note list row section-->
  <div class="row">
    <div class="col-lg-6">
      <div class="list-group">
        {% for note in note_list %}
        <div class="list-group-item {% if note.isCompleted %} note-complete {% endif %}">
          <form style="display: inline;" method="post" action="{% url 'notes:update' note.id %}">
            {% csrf_token %}
            <input type="checkbox" name="isCompleted" onchange="this.form.submit()" {% if note.isCompleted %} checked
              {% endif %} class="note-status-checkbox"
              title="{% if not note.isCompleted %} mark as done {% else %} mark undone {% endif %}">
          </form>
          <div class="note-title">{{ note.title }}</div>
          <div class="note-options">
            <a href="{% url 'notes:edit' note.id %}" title="Edit">
              <i class="far fa-edit"></i>
            </a>
            <a href="{% url 'notes:delete' note.id %}" title="Delete">
              <i class="far fa-trash-alt"></i>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<!-- JavaScript for theme toggle button section -->
<script>
  function toggleTheme() {
    const body = document.body;
    body.classList.toggle("dark-mode");
    const button = document.getElementById("theme-toggle");
    if (body.classList.contains("dark-mode")) {
      button.innerHTML = '<i class="fas fa-sun"></i> Light Mode';
    } else {
      button.innerHTML = '<i class="fas fa-moon"></i> Dark Mode';
    }
  }
  const themeToggle = document.getElementById("theme-toggle");
  themeToggle.addEventListener("click", toggleTheme);
</script>
{% endblock %}